### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amchagas**
update references such as email, program name etc to Open Hardware Makers

### CODE REVIEW

**Review by vektorious — APPROVED** [review]
:+1: Thanks Andre, I missed the README :see_no_evil: 

Anyways. Should we state somewhere that this is a copy of OL?

**Comment by amchagas** [comment]
I think stating somewhere this is derived from OL is a good idea!

**Comment by thessaly** [comment]
The contributors section is a bit confusing, as they are the contributors of the previous content. Can we just put a link to open leaders website and mention them, but use the bullet points for our contributors?

This is related to, maybe adding a section saying that this repo is a result of a global consultation process.

My proposal; I can accept and merge, and then make these changes, if you're OK with them..

**Comment by vektorious** [comment]
> The contributors section is a bit confusing, as they are the contributors of the previous content. Can we just put a link to open leaders website and mention them, but use the bullet points for our contributors?
> 
> This is related to, maybe adding a section saying that this repo is a result of a global consultation process.
> 
> My proposal; I can accept and merge, and then make these changes, if you're OK with them..

I'm OK with that!

**Review by thessaly — APPROVED** [review]

**Pull request merged**
